### ISSUE TITLE
Investigate why netty-codec-http2 and grpc-core are always downloaded.

### ISSUE THREAD

**Issue by nwbirnie** [googleads/google-ads-java#67] opened 2019-03-08 18:38 UTC
Investigate why netty-codec-http2 and grpc-core are always downloaded.

> 
> google-ads-examples (scratch) 10158$ mvn compile
> [INFO] Scanning for projects...
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Google Ads API client library for Java examples 0.7.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> Downloading: https://repo.maven.apache.org/maven2/io/grpc/grpc-core/maven-metadata.xml
> Downloaded: https://repo.maven.apache.org/maven2/io/grpc/grpc-core/maven-metadata.xml (1.8 kB at 2.9 kB/s)
> Downloading: https://repo.maven.apache.org/maven2/io/netty/netty-codec-http2/maven-metadata.xml
> Downloaded: https://repo.maven.apache.org/maven2/io/netty/netty-codec-http2/maven-metadata.xml (2.1 kB at 35 kB/s)

**Comment by jradcliff** [comment] 2019-03-22 20:49
I can no longer produce the output mentioned above, presumably because of dependency updates made in recent versions.

Closing this as not reproducible.

**Closed by jradcliff** 2019-03-22 20:49 UTC
