### ISSUE TITLE
Download report failed with RejectedExecutionException

### ISSUE THREAD

**Issue by softluna** [googleads/google-ads-java#579] opened 2022-02-28 04:05 UTC
**Describe the bug:**

download report  failed when  record count >= 10000

**Steps to Reproduce:**

code snippets:
 // get SearchPagedResponse
GoogleAdsServiceClient.SearchPagedResponse searchPagedResponse = googleAdsServiceClient.search(searchQuery);
// process response Row 
for (GoogleAdsRow googleAdsRow : searchPagedResponse.iterateAll()) {
   // inter biz code
}

**Expected behavior:**

**Client library version and API version:**
Client library version:  1.30.4
Google Ads API version:  v9
JDK version:  v16.0.0

**Request/Response Logs:**

 [grpc-default-executor-0] c.g.ads.googleads.lib.request.summary    : SUCCESS REQUEST SUMMARY. Method: google.ads.googleads.v9.services.GoogleAdsService/Search, Endpoint: googleads.googleapis.com:443, CustomerID: 3047363364, RequestID: fq8sgiBc_tkQvPWpKbMibw, ResponseCode: OK, Fault: null.
[grpc-default-executor-0] c.g.ads.googleads.lib.request.summary    : FAILURE REQUEST SUMMARY. Method: google.ads.googleads.v9.services.GoogleAdsService/Search, Endpoint: googleads.googleapis.com:443, CustomerID: 3047363364, RequestID: null, ResponseCode: UNAVAILABLE, Fault: Channel shutdown invoked.
 [grpc-default-executor-0] c.g.ads.googleads.lib.request.detail     : FAILURE REQUEST DETAIL.
Request
MethodName: google.ads.googleads.v9.services.GoogleAdsService/Search
Endpoint: googleads.googleapis.com:443

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1e88a8c4 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@51c71685[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
  at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
  at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
  at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
  at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
  at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator.schedule(MoreExecutors.java:651)
  at com.google.api.gax.retrying.ScheduledRetryingExecutor.submit(ScheduledRetryingExecutor.java:116)
  at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:137)
  at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
  at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
  at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1277)
  at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
  at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
  at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
  at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
  at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
  at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
  at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
  at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
  at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1277)
  at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
  at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
  at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
  at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
  at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
  at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
  at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
  at com.google.ads.googleads.lib.logging.LoggingInterceptor$1$1.onClose(LoggingInterceptor.java:113)
  at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
  at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
  at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
  at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
  at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
  at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:874)
  Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
    at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
    at com.google.api.gax.paging.AbstractPage.getNextPageImpl(AbstractPage.java:118)
    at com.google.api.gax.paging.AbstractPage.getNextPage(AbstractPage.java:91)
    at com.google.api.gax.paging.AbstractPage$AllResourcesIterator.computeNext(AbstractPage.java:177)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)

 
**Anything else we should know about your project / environment:**
java  SDK : 1.8

**Comment by devchas** [comment] 2022-03-01 21:14
Duplicate of #567 

Hi @softluna - this seems like the same issue as being addressed in #567 so I am marking this as a duplicate. Despite the two issues using different services, I believe the underlying cause is the same, so please follow along with the thread there where I've provided an answer.

**Closed by devchas** 2022-03-01 21:14 UTC
Labels: bug, triage
