### ISSUE TITLE
How to handle UNAUTHENTICATED errors

### ISSUE THREAD

**Issue by z0mg** [googleads/google-ads-java#786] opened 2024-03-27 18:41 UTC
Hi,

Does the library attempt to refresh the access token on its own? why is it failing and how can I fix this? 

```
com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Failed computing credential metadata
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:116)
        at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
        at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
        at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
        at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807)
        at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:568)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:570)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at com.google.ads.googleads.lib.logging.LoggingInterceptor$1$1.onClose(LoggingInterceptor.java:113)
        at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
        at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
        at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
                at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
                at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
                at com.google.ads.googleads.v15.services.KeywordPlanIdeaServiceClient.generateKeywordHistoricalMetrics(KeywordPlanIdeaServiceClient.java:355)
                at ........ internal stack
Caused by: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Failed computing credential metadata
        at io.grpc.Status.asRuntimeException(Status.java:537)
        ... 21 more
Caused by: java.lang.NoSuchMethodError: 'int com.google.api.client.http.HttpResponseException.getAttemptCount()'
        at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:124)
        at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:143)
        at com.google.auth.oauth2.UserCredentials.doRefreshAccessToken(UserCredentials.java:272)
        at com.google.auth.oauth2.UserCredentials.refreshAccessToken(UserCredentials.java:177)
        at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:269)
        at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:266)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:633)
        ... 3 more

```

Thank you.

**Comment by jradcliff** [comment] 2024-03-27 19:38
Hi,

The library will get a new access token if the current one is expiring, but that error you're seeing is unusual because something internal to the Google auth library is failing.

Could you share your dependencies (`mvn dependency:tree` or `./gradlew dependencies`)? That error suggests mismatched dependencies as a possible root cause of that error.

Thanks,
Josh, Google Ads API Team

**Comment by z0mg** [comment] 2024-03-28 08:36
The cause seems to be my outdated google-http-client, which didn't have the `getAttemptCount` method. I was reluctant to upgrade it, but it seems there is no other way to prevent this and refresh the access token myself - the library will just do it by itself, right?

**Comment by jradcliff** [comment] 2024-03-28 13:57
You could set the expiration and and refresh margins to a max value. For example:

```
      // Builds a GoogleAdsClient from a properties file in the usual way.
      GoogleAdsClient googleAdsClient = GoogleAdsClient.newBuilder().fromPropertiesFile().build();
      // Constructs new UserCredentials that have max refresh and expiration margin.
      UserCredentials credentials = ((UserCredentials) googleAdsClient.getCredentials()).toBuilder()
          .setRefreshMargin(Duration.ofDays(Integer.MAX_VALUE))
          .setExpirationMargin(Duration.ofDays(Integer.MAX_VALUE))
          .build();
      // Replaces the client with a new one with the alt credentials.
      googleAdsClient = googleAdsClient.toBuilder().setCredentials(credentials).build();
```

This might work, but at some point you will need to get a new access token, and presumably that will fail again with the same error. I'd recommend upgrading your dependencies if at all possible.

One of the easiest ways to make sure all your dependencies are consistent with each other is to use the [Cloud Client Libraries BOM](https://cloud.google.com/java/docs/bom). Version `30.0.0` of the Google Ads API library for Java is compatible with `com.google.cloud:libraries-bom:26.33.0`.

Thanks,
Josh, Google Ads API Team

**Comment by z0mg** [comment] 2024-03-29 10:18
Thank you very much for your help, Josh.

**Comment by jradcliff** [comment] 2024-03-29 13:12
You're welcome! I'll close this issue, but please reopen if you have further questions.

Cheers,
Josh, Google Ads API Team

**Closed by jradcliff** 2024-03-29 13:12 UTC
Labels: question
