### ISSUE TITLE
io. grpc.StatusRuntimeException: INTERNAL:Internal error encountered

### ISSUE THREAD

**Issue by Ashirkhan857** [googleads/google-ads-java#613] opened 2022-04-15 07:46 UTC
Hey, I faced this issue frequently when I ran multiple instances.
io. grpc.StatusRuntimeException: INTERNAL:Internal error encountered

**Comment by jradcliff** [comment] 2022-04-18 17:22
Closing as duplicate of #614

**Closed by jradcliff** 2022-04-18 17:22 UTC
Labels: bug, duplicate
