### ISSUE TITLE
internal_failure for OAuth requests with Google OAuth Java Library

### ISSUE THREAD

**Issue by igorschutbgenius** [googleads/google-ads-java#117] opened 2019-05-23 09:30 UTC
Requested by Google to post this issue on GitHub. Related issue is from https://groups.google.com/d/msg/adwords-api/394qh6XFwh4/SYLue6wbAgAJ

We saw a lot of authentication errors starting from the 2nd of May to the entire weekend (till 6th of May). Errors prompted occurred on OAuth token request while code did not change.
Token error response contains: "internal_failure". There are no more details, these errors pop up while requesting token information from Google. The "internal_failure" error is the whole message received from Google.

- Problem is no longer visible, but we did see a lot of errors from 2-6 may.
- Code did not change at our end, previously worked fine.
- Problem was random. Sometimes it failed with internal_failure errors and sometimes all requests are successful.
- Multiple accounts across different clients (and with different tokens).
- We use the official Google OAuth Java Library.
- We use Google AdWords Java Library to pull reports and push new items or updates to Google. Failures occurred randomly on both.
- Software is hosted in Amazon AWS, located in Ireland (saw some issues here before).

We're not seeing this error anymore but I would like to have this figured out. Our software relies heavily on Google Ads to push changes and lots of our clients do too.

Thanks,
Igor Schut

**Comment by nwbirnie** [comment] 2019-05-24 11:34
Hey, thanks for bringing this to our attention. This is likely an issue with the OAuth library's endpoints rather than Ads. Also based on the periodic nature of the report I would expect this was an outage affecting the backends there and we should take comfort in the fact that is has now been resolved. At Google we have a very robust post-mortem culture, so appropriate steps will be taken to identify, fix and prevent the root cause from rematerializing.

I'll reach out to the OAuth team to confirm this understanding. Closing this issue for just now, but will reopen if further action is required.

Best wishes,
Nick

**Comment by nwbirnie** [comment] 2019-05-24 16:56
Quick follow up on this one, could you please email googleadsapi-support@google.com - mention my name - and pass them your OAuth client ID. Also please include the manager account ID your developer token is associated with. We'd like to take a closer look to understand what happened here.

**Comment by nwbirnie** [comment] 2019-06-04 16:52
Discussed over email - most logs are now gone from that period and from what's left we didn't see any spike in errors.

Feel free to reopen if issue recurs.

**Closed by nwbirnie** 2019-06-04 16:52 UTC
